FROM php:8.3-fpm

RUN apt-get update && apt-get install -y \
    libzip-dev unzip git strace \
    && docker-php-ext-install pdo pdo_mysql zip opcache

COPY infra/docker/php/php-opcache-only.ini /usr/local/etc/php/php.ini
COPY infra/docker/php-fpm/www-static-default.conf /usr/local/etc/php-fpm.d/www.conf

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/pdp

# Копируем shared директорию с тестами
COPY shared shared

