FROM golang:1.25.5-alpine AS builder

WORKDIR /app

COPY services/go-service/go.mod ./
COPY services/go-service/go.sum* ./

RUN go mod download

COPY services/go-service ./

RUN CGO_ENABLED=0 GOOS=linux go build -o go-service ./cmd/main.go

FROM alpine:3.20

RUN apk --no-cache add ca-certificates

WORKDIR /app

COPY --from=builder /app/go-service .

EXPOSE 8090

CMD ["./go-service"]

