FROM php:8.3-fpm

RUN apt-get update && apt-get install -y \
    libzip-dev unzip git curl \
    && docker-php-ext-install pdo pdo_mysql zip opcache

# Копируем API файл
COPY services/api-gateway/api.php /var/www/pdp/api.php

WORKDIR /var/www/pdp

EXPOSE 9000

